name: dynamic-test-matrix

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  matrix:
    name: Generate subdir matrix
    runs-on: ubuntu-latest
    outputs:
      matrix-json: ${{ steps.set-matrix.outputs.matrix }}
    steps:
      - name: generate matrix value
        id: set-matrix
        run: |
          #set variable with subdirectories
          SUBDIRS=( $(find -maxdepth 1 -type d) )
          # Set output
          echo "::set-output name=matrix::$( echo $SUBDIRS )"
          
  run-matrix:
    needs: [matrix]
    strategy:
      fail-fast: false
      matrix:
        include: ${{ toJSON(needs.matrix.outputs.matrix-json) }}
    name: "${{ matrix.job_name }}"
    runs-on: ${{ matrix.os }}
    steps:
     - run: echo ${{needs.matrix.outputs.matrix-json}}
