name: dynamic-test-matrix

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  matrix:
    name: Generate subdir matrix
    runs-on: ubuntu-latest
    outputs:
      matrix-output: ${{ steps.set-matrix.outputs.matrix }}
    steps:
      - name: generate matrix value
        id: set-matrix
        run: |
          readarray -t array <<< "$(find -maxdepth 1 -type d)";
          # Set output
          echo "::set-output name=set-matrix::$array"
          
  run-matrix:
    needs: [matrix]
    strategy:
      fail-fast: false
      matrix: ${{ needs.matrix.outputs.matrix-output }}
    name: "${{ matrix.job_name }}"
    runs-on: ${{ matrix.os }}
    steps:
     - uses: actions/checkout@v2
     - name: Run command
       shell: bash
       run: echo ${{ needs.matrix.outputs.matrix-output }}
